
spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: bmV3c2ZlZWQtand0LXNlY3JldC1rZXluZXdzZmVlZC1qd3Qtc2VjcmV0LWtleQ==

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: bmV3c2ZlZWQtand0LXNlY3JldC1rZXluZXdzZmVlZC1qd3Qtc2VjcmV0LWtleQ==